### PR TITLE
Threading

### PR DESCRIPTION
**Pull request by parenthetical**
- [ ] Decide what to do about how tags and replies interact (show no tag on the message?)
- [ ] Clean up tags being threaded through the code for no use in replies
- [ ] UX regarding infinite replies?

### CODE REVIEW

**Comment by stevekrouse** [comment]
Awesome!!!

One issue I found is that you don't close the reply box after I send the reply:

Screen Shot 2021-12-14 at 2 00 14 PM

The other issue is that the tags don't seem to work 3 levels deep. You can see if you go to #intro in the preview link the third message doesn't show up:

Screen Shot 2021-12-14 at 2 00 33 PM

**Comment by parenthetical** [comment]
There's some confusion between tags and channels about which we might as well think now. Would a reply ever have different tags from a parent?

**Comment by stevekrouse** [comment]
From a simplicity perspective, I want the best of all worlds:

1. replies can be totally unrestricted in the tags they have
2. replies always show up in the channel of their parent

It could make sense to always add the tag of the parent to every child. Or we can do it without that.

What do you think?

**Comment by parenthetical** [comment]
I removed tags from replies altogether since doing anything else was breaking my brain. This is mergeable now I'd say.

We could add tags to replies once we decide what that actually means or how they would be used? Right now adding tags to replies would only add the little tag boxes but otherwise have no effect on the app.

**Pull request merged**
